// @OUTPUT_FILE@ — @VARIANT_LABEL@
// MIT License. Generated by scripts/build-variants.mjs.
// Single pass, one terminal sample, analytic folds. No noise or feedback buffers.
// AURORA_INTENSITY keeps compatibility with the existing preset switcher.
const float AURORA_INTENSITY = @AURORA_INTENSITY@;
const float SILK_SPEED = 0.22;
const float TEXT_PROTECT = 1.0;
const int SILK_FOLDS = @SILK_FOLDS@;

vec3 silkField(vec2 uv, float time) {
    float aspect = iResolution.x / max(iResolution.y, 1.0);
    vec2 p = vec2((uv.x - 0.5) * aspect, uv.y - 0.5);
    float t = time * SILK_SPEED;
    vec3 light = vec3(0.0);

    for (int i = 0; i < SILK_FOLDS; i++) {
        float k = float(i);
        // Long diagonal folds bend together, with a slightly different phase.
        float bend = 0.18 * sin(p.y * 3.1 + t * 0.65 + k * 0.82);
        bend += 0.065 * sin(p.y * 6.0 - t * 0.48 + k * 1.7);
        float center = (k - float(SILK_FOLDS - 1) * 0.5) * 0.37;
        float d = p.x + p.y * 0.46 - center - bend;
        float width = 0.10 + 0.022 * sin(p.y * 2.7 + k + t * 0.38);
        float body = exp2(-d * d / (width * width) * 1.15);
        float lip = d - width * 0.55;
        float sheen = exp2(-lip * lip / (width * width) * 14.0);
        float shadow = smoothstep(-width * 1.8, width * 0.8, d);
        float weave = 0.97 + 0.03 * sin(d * 165.0 + p.y * 8.0);
        vec3 champagne = vec3(0.64, 0.49, 0.35);
        vec3 pearl = vec3(0.43, 0.39, 0.64);
        vec3 tint = mix(champagne, pearl, 0.5 + 0.5 * sin(k * 1.9 + p.y * 1.2));
        light += tint * (body * (0.11 + shadow * 0.25) + sheen * 0.24) * weave;
    }

    // Keep the edges quiet without crushing the underlying terminal colors.
    float falloff = 1.0 - 0.32 * smoothstep(0.25, 1.2, length(p * vec2(0.55, 0.85)));
    return light * falloff;
}

void mainImage(out vec4 fragColor, in vec2 fragCoord) {
    vec2 uv = fragCoord / iResolution.xy;
    vec4 terminal = texture(iChannel0, uv);
    float peak = max(terminal.r, max(terminal.g, terminal.b));
    float luma = dot(terminal.rgb, vec3(0.2126, 0.7152, 0.0722));
    float edge = max(fwidth(peak), fwidth(luma));
    float glyph = smoothstep(0.012, 0.075, edge) * TEXT_PROTECT;
    // Protect saturated ANSI text as well as bright text and light themes.
    float background = 1.0 - smoothstep(0.16, 0.40, peak);
    float mask = background * (1.0 - glyph);
    vec3 light = silkField(uv, iTime) * AURORA_INTENSITY;
    fragColor = vec4(terminal.rgb + light * mask * terminal.a, terminal.a);
}
